apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data-pv/python-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: python-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api-deployment
  labels:
    app: python-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: ajinkya1311/python-api:1.0.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/data/python-app"
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: python-app-pvc
